version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - dotnet restore .\src
      - dotnet build .\src

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - .\bin\Debug\netcoreapp3.1\*