version: 0.2

phases:  
  build:
    commands:
      - echo Build started on `date` in $pwd
      - cd src
      - dotnet restore 
      - dotnet build
      - dotnet test
    
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - .\bin\Debug\netcoreapp3.1\*