version: 0.2

phases:  
  build:
    commands:
      - echo Build started on `date` in $pwd
      - cd src
      - dotnet restore 
      - dotnet build
      - dotnet test --collect:"XPlat Code Coverage" --logger trx
    
  post_build:
    commands:
      - echo Build completed on `date`
reports:
  test-reports:
    files:
      - "src/TacoChat.Test/TestResults/*.trx"
    file-format: "VISUALSTUDIOTRX"
  code-coverage:
    files:
      - "src/TacoChat.Test/TestResults/*/*.xml"
    file-format: "COBERTURAXML"

artifacts:
  files:
    - .\bin\Debug\netcoreapp3.1\*